---
abstract: 'Currying of subroutines via a new ''curry' declarator'
author:
  - osfameron
build_requires:
  Test::Exception: 0.00
  Test::More: 0.42
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Sub-Curried
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0.00
  Devel::Declare: 0.00
  Sub::Name: 0.00
version: 0.02
