---
abstract: 'automatically curried subroutines'
author:
  - osfameron
build_requires:
  Test::Exception: 0.00
  Test::More: 0.42
  Test::NoWarnings: 0.00
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Sub-Curried
no_index:
  directory:
    - inc
    - t
    - examples
    - examples
requires:
  B::Hooks::EndOfScope: 0.00
  Carp: 0.00
  Devel::BeginLift: 0.00
  Devel::Declare: 0.002000
  Sub::Current: 0.00
  Sub::Name: 0.00
version: 0.10
